from tools.plots.chromatin_differential_plot import plot_chromatin_differential, plot_scatter_chromatin_differential
# from tools.plots.streamplot import plot_stream
from tools.plots.factor_influence_plot import plot_factor_influence, compare_driver_TFs_plot
from tools.plots.enrichment_plot import plot_enrichments
from tools.plots.eigengap_plot import plot_eigengap
